# Generated by Django 4.1.5 on 2023-01-10 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bus.busstop'),
        ),
    ]
