# Generated by Django 4.1.5 on 2023-01-11 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0004_alter_bus_bus_stop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='name',
            new_name='Bus_name',
        ),
    ]
