# Generated by Django 4.1.5 on 2023-01-11 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_rename_name_bus_bus_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='Bus_name',
            new_name='bus_name',
        ),
    ]
