# Generated by Django 4.1.5 on 2023-01-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0006_rename_bus_name_bus_bus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstop',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
