# Generated by Django 4.1.5 on 2023-01-12 09:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0010_alter_bus_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='bus_stop',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='time',
        ),
        migrations.CreateModel(
            name='BusTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.bus')),
                ('bus_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.busstop')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
