# Generated by Django 4.1.5 on 2023-01-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0011_remove_bus_bus_stop_remove_bus_time_bustime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bustime',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
